sudo: false

language: cpp

git:
  depth: false

cache:
  ccache: true

# Build on pull request or push to:
#  - branches explicitly listed

branches:
  only:
    - 0.3.X
    - 1.0.X

jobs:
  include:

    # stage 1:
    #  Run tests

    # test on linux
    - stage: test_it
      os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - bash-completion
            - curl
      install:
        - bash $TRAVIS_BUILD_DIR/build_scripts/travis-install.sh
      script:
        - echo "test_it on $TRAVIS_OS_NAME"
        - bash $TRAVIS_BUILD_DIR/build_scripts/travis-script.sh

    # test on osx
    - stage: test_it
      os: osx
      osx_image: xcode11.6
      compiler: clang
      install:
        - bash $TRAVIS_BUILD_DIR/build_scripts/travis-install.sh
      script:
        - echo "test_it on $TRAVIS_OS_NAME"
        - bash $TRAVIS_BUILD_DIR/build_scripts/travis-script.sh

    # stage 2:
    #  If tests pass, and this is a merge or push to primary development branches, then we will
    #    upload updated conda packages

    # primary linux package
    - stage: package_it
      if: env(CASM_CONDA_ID_USER) IS present AND type = push
      os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - bash-completion
            - curl
      script:
        - echo "package_it on $TRAVIS_OS_NAME"
        - bash $TRAVIS_BUILD_DIR/build_scripts/travis-build-conda.sh

    # osx package
    - stage: package_it
      if: env(CASM_CONDA_ID_USER) IS present AND type = push
      os: osx
      osx_image: xcode11.6
      compiler: clang
      script:
        - echo "package_it on $TRAVIS_OS_NAME"
        - bash $TRAVIS_BUILD_DIR/build_scripts/travis-build-conda.sh
